# 选择你要使用的 docker 镜像
image: node:20-buster

pages:
  # 每当 push 到 main 分支时触发部署
  only:
    - master

  # 缓存 node_modules
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

  # 安装依赖并运行构建脚本
  script:
    - npm ci
    - npm run build -- --dest dist

  artifacts:
    paths:
      - dist